# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bootstrap class for Stochastic Volatility (SV) model
#' 
#' Initialised with a data vector of observations (Yt), an estimate mean and 
#' standard deviation parameter and rho controls the autocorrelation.
#' 
#' The object defines methods to sample from the initial distribution M0 and 
#' the subsequent transition kernels Mt and calculate the log probability from 
#' the potential function Gt.
#' @name Bootstrap_SV_C
#' @export Bootstrap_SV_C
#' @exportClass Bootstrap_SV_C
#' @field data vector of observations
#' @field mu estimate of mean of latent var (float)
#' @field sigma estimate of sd of latent
#' @field rho autocorrelation parameter
NULL

#' Bootstrap filter
#' 
#' Implements a bootstrap particle filter.
#' Takes an object of class Bootstrap_SV_C as argument, with number of particles
#' N and number of time steps to run.
#' @name bootstrap_filter_rcpp
#' @export bootstrap_filter_rcpp
#' @field fk_model Bootstrap_SV_C object
#' @field N number of particles
#' @field tmax number of steps
NULL

#' Effective Particle Number
#' 
#' Uses the weight vector input to compute an estimate of effective particle number for use in particle filters.
#' @name eff_particle_no
#' @export eff_particle_no
#'
#' @field w vector of weights
eff_particle_no <- function(w) {
    .Call(`_smc_eff_particle_no`, w)
}

#' Systematic resampling algorithm
#' 
#' Samples a single uniform random variable U and then assigns values U(n) = (n - 1 + U)/N.
#' Used to generate a vector of integers to index the particles.
#' @name systematic_resampling_rcpp
#' @export systematic_resampling_rcpp
systematic_resampling_rcpp <- function(W) {
    .Call(`_smc_systematic_resampling`, W)
}

