# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

systematic_resampling_rcpp <- function(W) {
    .Call(`_smc_systematic_resampling`, W)
}

parallelVectorSum <- function(x) {
    .Call(`_smc_parallelVectorSum`, x)
}

