# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_bootstrap_filter <- function(data, mu, sigma, rho, N, tmax) {
    .Call(`_smc_run_bootstrap_filter`, data, mu, sigma, rho, N, tmax)
}

parallelVectorSum <- function(x) {
    .Call(`_smc_parallelVectorSum`, x)
}

